# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

os: linux
arch: arm64
dist: bionic
language: minimal

addons:
  apt:
    packages:
      - libgit2-dev
      - python3-pip
      - rake

services:
  - docker

# don't build twice
if: tag IS blank

env:
  global:
    - APT_TARGETS={{ target }}
    - ARROW_VERSION={{ arrow.version }}
    - BUILD_REF={{ arrow.head }}
    - TRAVIS_TAG={{ task.tag }}
    - YUM_TARGETS={{ target }}

before_script:
  - git clone --no-checkout {{ arrow.remote }} arrow
  - git -C arrow fetch -t {{ arrow.remote }} {{ arrow.branch }}
  - git -C arrow checkout FETCH_HEAD

script:
  - pushd arrow/dev/tasks/linux-packages
  - rake version:update
  - |
    rake docker:pull || :
  - |
    stdbuf --output=0 \
      rake \
        BUILD_DIR=build \
        DEB_BUILD_OPTIONS=parallel=8 \
        RPM_BUILD_NCPUS=8 \
        {{ build_task }}
  - sudo rm -rf */*/build
  - popd

after_success:
  - pushd arrow/dev/tasks/linux-packages
  - |
    docker login -u "${DOCKERHUB_USER}" \
                 -p "${DOCKERHUB_TOKEN}" || :
  - |
    rake docker:push || :
  - popd
  - |
    sudo -H pip3 install \
      "click>=7.1" \
      github3.py \
      jinja2 \
      jira \
      pygit2==0.26.4 \
      ruamel.yaml \
      setuptools_scm \
      toolz
  - |
    python3 arrow/dev/tasks/crossbow.py \
      --queue-path . \
      --queue-remote {{ queue_remote_url }} \
      upload-artifacts \
    {%- for extension in upload_extensions %}
      --pattern "**/*{{ extension }}" \
    {%- endfor %}
      --sha {{ task.branch }} \
      --tag {{ task.tag }}
